## Business Problem - Predict the Price of Bangalore House

In [99]:
import pandas as pd
import numpy as np

In [100]:
path = r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB" 
df = pd.read_csv(path)
df.head()

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.0,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.0,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,150.0,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,40.0,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,83.0,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [101]:
X = df.drop('price',axis =1)
Y = df['price']
X.shape

(7120, 107)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7120 entries, 0 to 7119
Columns: 108 entries, bath to location_Tumkur Road
dtypes: float64(5), int64(103)
memory usage: 5.9 MB

In [103]:
df.describe()

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
count,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,...,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000
mean,2.390871,1.572759,96.454991,1479.729806,2.465169,5923.806855,0.750702,0.182303,0.061938,0.792697,...,0.003090,0.003090,0.002949,0.002949,0.002949,0.002949,0.002809,0.002809,0.002809,0.002809
std,0.876822,0.770583,116.185034,913.779769,0.841520,2556.650935,0.432637,0.386121,0.241060,0.405403,...,0.055505,0.055505,0.054232,0.054232,0.054232,0.054232,0.052929,0.052929,0.052929,0.052929
min,1.000000,0.000000,10.000000,350.000000,1.000000,1250.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,1.000000,49.230000,1100.000000,2.000000,4416.761042,1.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,2.000000,69.000000,1255.000000,2.000000,5417.855613,1.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3.000000,2.000000,104.000000,1640.250000,3.000000,6618.285651,1.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,9.000000,3.000000,2912.000000,30400.000000,9.000000,35000.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [104]:
df.isnull().sum()

bath                           0
balcony                        0
price                          0
total_sqft_int                 0
bhk                            0
                              ..
location_Hosur Road            0
location_Horamavu Banaswadi    0
location_Domlur                0
location_Mahadevpura           0
location_Tumkur Road           0
Length: 108, dtype: int64

In [105]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train,Y_test = train_test_split(X,Y,test_size = .2, random_state = 51)

In [106]:

X_train.shape

(5696, 107)

In [107]:
from sklearn.svm import SVR

Feature Scaling

In [108]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)

StandardScaler()

In [109]:
X_train = sc.transform(X_train)
X_test =sc.transform(X_test)

In [110]:
svr_poly = SVR(kernel='poly',degree=2)
svr_poly.fit(X_train, Y_train)
svr_poly.score(X_test, Y_test)

0.18266215211874637

In [111]:
svr_linear = SVR(kernel='linear')
svr_linear.fit(X_train, Y_train)
svr_linear.score(X_test, Y_test)

0.7962656700653191

In [112]:
svr_rbf = SVR(kernel='rbf')
svr_rbf.fit(X_train, Y_train)
svr_rbf.score(X_test, Y_test)

0.20638035840828173

## Predict the value of Home and Test

In [113]:
X_test[0]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06226825,
       -0.05935999, -0.05935999, -0.05935999, -0.05630391, -0.05935999,
       -0.05785186, -0.05935999, -0.05935999, -0.06083125, -0.06083125,
       -0.05471275, -0.06083125, -0.06226825, -0.05935999, -0.05935999,
       -0.06226825, -0.06226825, -0.05785186, -0.06504853, -0.06226825,
       -0.06083125, -0.05935999, -0.05307449, -0.05630391, -0.06226825,
       -0.05471275, -0.05935999, -0.05471275, -0.05471275, -0.05138463,
       -0.05307449, -0.05307449, -0.05471275, -0.05471275, -0.05630391,
       -0.05630391, -0.05138463])

In [116]:
Y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [115]:
svr_linear.predict([X_test[0]])

array([86.53643947])